### ISSUE TITLE
Internal Server Error:Issue while posting for Merchant Mappings

### ISSUE THREAD

**Issue by farhanbutt18** [Mastercard/mastercard-api-client-tutorial#18] opened 2021-05-25 11:41 UTC
Hello, I have implemented this client code (csharp) for the **Mastercard merchant mappings**, getting an 'Internal Server Error' in response while posting the request to **Mastercard Directory Services** as it includes encryption and decryption.
Unfortunately, there isn't a lot of details in the error:
Response:
{"Errors":{"Error":[{"Source":"SYSTEM","ReasonCode":"SERVICE_ERROR","Description":"","Recoverable":false}]}}

P.S. I am getting a successful response while fetching an existing sample mapping record.
Support isn't helpful yet so... Thanx in advance.

**Comment by TutteRamson** [comment] 2021-05-25 12:00
@farhanbutt18, as this isn't an issue with the signing or encryption library per se, we suggest you get in touch with the [Support Team](https://developer.mastercard.com/support/). They in turn will reach out to the specific backend service and sort out the internal server error. 

When you reach out to the support team, please provide them with the full wire logs showing the request and response, along with timestamps.

**Comment by TutteRamson** [comment] 2021-05-26 11:02
Closing the issue. Please create one if the problem is specific to the signing or encryption library.

**Closed by TutteRamson** 2021-05-26 11:02 UTC
